[package]
name = "lsearch-core"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
globset = "0.4.18"
itertools = "0.14.0"
tempfile = "3.23.0"
tokio = { version = "1", features = ["full"] }
